### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by CoreyKaylor**
Here is my first pass at refactoring a few things. I'll next move onto the NUnit conversion and rake tasks if this is goes over well. Let me know your thoughts.

### CODE REVIEW

**Comment by CoreyKaylor** [comment]
Closes #6

**Comment by ilyalukyanov** [comment]
Hi, Corey, thank you, i've looked through your changes. Everything looks fine and i'm going to merge it this evening. Please read my comments and tell me your thoughts. I think i will do additional changes (pointed in comments) myself to save some of your time.
Did you ran tests after these changes? Were they all green?

**Comment by CoreyKaylor** [comment]
Yes, they were green. I like all of your suggestions and comments.

**Comment by CoreyKaylor** [comment]
Also a bit relieved to hear your comments on the memory leak. I was concerned when I couldn't find a way to explicitly release that memory either in the API itself or the Marshal class.

**Pull request merged**
