### PR TITLE
Build macOS dylib, use netcoreapp2.0 for test

### PR DESCRIPTION
**Pull request by zone117x**
Let me know if you want any of these changes broken down into smaller pull requests.

### CODE REVIEW

**Comment by CoreyKaylor** [comment]
I'm not interested in exposing the static DllImport methods. The other stuff looks fine to me though. I still need to track down the latest approach for this all to work on travis. I haven't had enough time to invest here. Any ideas?

**Comment by zone117x** [comment]
Ah, I didn't intend for that last commit exposing the dllimports to make in this pull.
Although it is really useful for tight loops where we need to make direct calls without the bit of overhead from the wrapper, as well as a few edge use cases that are not possible to do well through the wrapper. It would be nice to get that in so I can use the nuget package rather than having to reference my fork through a git submodule. 

MacOS build/test servers (especially free ones) are notoriously annoying to find and setup due to Apple's licensing system. I've had no luck finding one the past couple years for dylib compiling or Xamarin.Mac lib compiling. Although I haven't looked again for a year or so. Please do let me know if you find one.

**Comment by Jotune** [comment]
Any update on this ? I'm eager to port an app using lmdb to .net standard 2.0

**Comment by zone117x** [comment]
I have since seen TravisCI used for testing netcore on MacOS. It requires pulling and install the dotnet core pkg during the build process. If you search around there are a few projects that have the travis config files to do it. I' recommend merging this anyway though.

**Pull request closed without merging**
