### PR TITLE
Added dnx strategy for LoadLibrary

### PR DESCRIPTION
**Pull request by CoreyKaylor**
Converted project structure to dnx.
Removed ripple, and ruby / rakefile dependencies.

Opening this pull request for an open discussion as I make changes if anybody is interested or has better ideas. I don't plan to have this merged in soon because it _somewhat_ requires VS 2015 RC, although you can run the dnx stuff without updating VS itself.

Currently the tests pass on Windows and I will be testing on my Mac again soon.

To test out the changes...
`dnvm use 1.0.0-beta4`
`dnu restore`
`dnx tests/LightningDb.Tests test`

NOTE: I will be rebasing this branch as changes get pulled into master. You have been warned.

### CODE REVIEW

**Comment by CoreyKaylor** [comment]
I've got the AppVeyor build working now. I'll be moving to make the myget feed work next. I know there will be a few challenges with the new way for install.ps1 to be included as it was before. I have a couple idea to try out. If it ends up working out the build process will be a whole lot simpler now. :smile:

**Comment by CoreyKaylor** [comment]
Successfully publishing from AppVeyor to myget feed now. Next onto *nix compatibility and Travis CI.

https://www.myget.org/F/lightning-net/api/v2/Packages

**Comment by CoreyKaylor** [comment]
The following tests cause the process to crash on my Mac with mono. It appears it's due to the MarshallMultipleValueStructure.Dispose. Even though there is an empty catch block it's not catching on mono when trying to free an allocation that was never made. I'm guessing there is a more elegant solution to ensure that we're not freeing an allocation for something that was never made.

   LightningDB.Tests.CursorTests.ShouldMoveNextMultiple [SKIP]
      Not working on mono
   LightningDB.Tests.CursorTests.ShouldPutMultiple [SKIP]
      Not working on mono
   LightningDB.Tests.CursorTests.ShouldGetMultiple [SKIP]
      Not working on mono
   LightningDB.Tests.TransactionTests.TransactionShouldSupportCustomDupSorter [SKIP]

**Comment by CoreyKaylor** [comment]
I found a _fix_ for the MarshallMultipleValueStructure.cs on mono. The pointer that is being used in Dispose is changing for some reason between initialization and dispose. I'm not exactly sure why that's happening right now, but the latest push caches the original pointer instead of referencing the one from the array and that seems to work.

**Comment by CoreyKaylor** [comment]
I verified for me at least that the behavior doesn't happen on Windows.

**Comment by CoreyKaylor** [comment]
Looks like I don't have enough privileges to setup travis CI for this repo. @ilyalukyanov Would you like to take care of this? I added the necessary yml file and it _should_ just work, but as with most CI's it might take a few tries to get it just right.

**Comment by CoreyKaylor** [comment]
The latest change to the way things are marshalled fixes the oddity with mono and the memory address changing. This also removes the need to copy values to the native lib and should perform a bit faster.

**Comment by CoreyKaylor** [comment]
I've gotten a bit impatient and forked the project to see the Linux CI through. It's now green on both AppVeyor and Travis.

**Comment by ilyalukyanov** [comment]
Hi @CoreyKaylor million appologies for ignoring this PR for this long... Having insanely busy time. 

You have done really great job on this! From the first look all code decisions are as we discussed previouslty. Anyway I cannot find anything I disagree with. Thank you!

I'll try to setup Travis and AppVeyor and then share links here.

**Comment by ilyalukyanov** [comment]
Currently both CI systems are failing with `Unable to locate Microsoft.Framework.CommandLineUtils.Sources >= 1.0.0-beta5`

**Comment by ilyalukyanov** [comment]
Ah I see, This is because dnx was updated. I see you addressed many issues caused by the new version in your fork. Could you please push your changes here?

I actually don't mind transfering ownership of this repo to you if you like. I feel really bad about slowing your down.

**Comment by CoreyKaylor** [comment]
Travis-CI will still fail for the missing nuget. AppVeyor should pass. dnu restore doesn't seem to be respecting the NuGet.config the same way that it does on Windows at the moment. I'm sure I can work through this. It does work locally on my Mac though, so it's likely something specific to dnu on Linux. They will likely publish that nuget as well I would think.

**Comment by CoreyKaylor** [comment]
I did a force push, because some of your commits for travis and the merged pull request were things already taken care of in my version of this branch.

I'm fine if you want to transfer ownership, but it's your call. Regarding the other issue of converter's I raised I'll plan on including that here as well because I have a branch locally almost ready to push that really simplifies the project overall and improves upon the cursor implementation. A few more items to push through and then I'll push things up here again.

**Comment by CoreyKaylor** [comment]
I will still need to scrub through the code and restore some previous comments if in my flurry have been lost. I plan to make sure that there is test coverage for most of the API as well before I'm complete. 

I'll also see what can be done as a workaround for Travis-CI as well..
The AppVeyor build failure is because the yml file I have embedded my api-key encrypted in isn't authorized for your myget feed.

**Comment by CoreyKaylor** [comment]
I lied, the nuget publish is failing because your appveyor version number hasn't caught up to the ones I've already published with and rejecting it because it has already been used. We also don't want the pull request actually going through the publish workflow. Supposedly appveyor already accounts for this. Might be a good idea to turn it off for pull requests until we figure out why that's happening...

**Comment by CoreyKaylor** [comment]
Looks like MS just published the missing nuget and the travis-ci build passes again for my repo.

**Comment by CoreyKaylor** [comment]
I think my tentative plan is that this pull request should stay open until July 20th when VS 2015 gets released. That way we're not expecting any contributors to have pre-release VS. Regardless of whether or not dnx is still pre-release the nuget will still support 4.5, and roslyn itself is RTM and shouldn't impact those consuming through that channel.

**Comment by ilyalukyanov** [comment]
Confirm, works for me. I switched off my CIs so should be fine now.

I'm happy to transfer ownershep to you =) I really cannot commit to actively paticipating in this project so see no reason in holding it. Which repo name would you like me to target?

**Comment by CoreyKaylor** [comment]
I'm not sure what you're asking, but if it's easier we can just use my fork as the primary repo if you would like? Not sure if that's what you were referring to though.

**Comment by CoreyKaylor** [comment]
When you get a chance I'll also need access to the public nuget as well.

**Comment by ilyalukyanov** [comment]
Sorry I was unclear. I mean, I tried to transfer ownership of the repo to you, but as the repo Lightning.NET already exists in your account I cannot transfer it with the same name. Either my repo or your fork should be renamed in order to let the transfer happen)

P.S. I added you as an owner to the NuGet package.

**Comment by CoreyKaylor** [comment]
Okay, I've renamed my fork and confirmed the nuget package request. Thanks for doing that.

**Comment by ilyalukyanov** [comment]
Damn.. now it says "CoreyKaylor already has a repository in the ilyalukyanov/Lightning.NET network". It seems that you shouldn't have any fork of this repo in order to allow the transfer =(

**Comment by CoreyKaylor** [comment]
I deleted my fork now.

**Comment by ilyalukyanov** [comment]
Cool! now it's successful and waits an approval on your side

**Comment by CoreyKaylor** [comment]
Looks like it went through successfully. Thanks again.

**Comment by CoreyKaylor** [comment]
This has been rebased and merged to master now after verifying everything worked with VS 2015 RTM.

**Pull request closed without merging**
