### PR TITLE
Converters alternative to providers base classes and static state

### PR DESCRIPTION
**Pull request by CoreyKaylor**
There is still more work to be done and a couple failing tests I have to work through, but this is where I was heading and wanted to post for comments and review.

Before this gets pulled in I will have a lot more test coverage over cursors, etc. I expect to be able to finish this off tomorrow afternoon.

### CODE REVIEW

**Comment by CoreyKaylor** [comment]
Related to #12

**Comment by ilyalukyanov** [comment]
Corey, these changes are good. Let me know when you are done and then I'll merge it.

**Comment by CoreyKaylor** [comment]
Just coming back to this finally. Looks like you found my typo. This can safely get merged in and would probably be good to do so before all the other refactoring changes. That is if you agree. I can make a separate pull request for more test coverage on top of your other stuff if that would be easiest.

**Comment by ilyalukyanov** [comment]
Ok, Corey, lets do so. It looks like the easiest way.

**Pull request merged**
