### PR TITLE
Respect NoSubDir flag; fixes issue #78

### PR DESCRIPTION
**Pull request by DanielAdolfsson**
Just a check to make sure the NoSubDir flag isn't set.

### CODE REVIEW

**Comment by DanielAdolfsson** [comment]
You mean you think it should create the parent directory? Isn't that a bit outside what's expected of a library that deals with individual files though?

**Comment by CoreyKaylor** [comment]
@ilyalatt I'm not sure that's true. Mind adding more clarification to your thoughts?

**Comment by CoreyKaylor** [comment]
@DanielAdolfsson Not a big deal this time, but in the future it's a safer bet to send a PR from a branch that isn't master.

**Comment by ilyalatt** [comment]
Then why default behavior is creating directory that doesn't exist? I think that in both cases behavior should be equal.

**Comment by CoreyKaylor** [comment]
Yeah, I don't feel as strong about that behavior for this scenario.

**Pull request merged**
