### PR TITLE
Added support for Unix with Mono.Net

### PR DESCRIPTION
**Pull request by drr00t**
Hi,

Greate work, i made few change to build on Mono.Net i added a binary version of lmdb for Linux x64 gcc-4.8.
- LightningCompareDelegate.cs: just a simple comment
- LightningDB.csproj: - removed a missing file to build LightningDB
  project
- LightningTransaction.cs:
- MultipleGetByOperation.cs: 
- Native.cs: added support for Unix with Mono.Net.
- NativeLibraryFacades.cs: facade with new specialization
- NativeLibraryFacades.tt: added support for unix native facade
  gererate
- LightningDB.Tests.csproj: added support to nuget for
  nunit.framework
- packages.config: nuget reference file for nunit

### CODE REVIEW

**Comment by drr00t** [comment]
Hi,

I miss the liblmdb64.so library file.

**Comment by ilyalukyanov** [comment]
Hi, thank you for your contribution, but unfortunately there're reasons why I cannot merge this PR:
- NuGet packages are managed by ripple, so changes to `LightningDB.Tests.csproj` and `packages.config` should be reverted.
- `CommonAssemblyInfo` shouldn't be removed from the system as it's automatically generated by the build system so changes to `LightningDB.csproj` should b reverted.
- Are you sure that the library doesn't work on mono? According to this http://www.mono-project.com/docs/advanced/pinvoke/#library-names it's enough to specify `lmdb32` and it will pickup lmdb32.dll, liblmdb32.so on Linux and liblmdb32.dylib on Mac.
- Not sure if we should store .so file in the repo as depending on what Linux distribution is used the file might be useless.

**Comment by CoreyKaylor** [comment]
I agree the existing approach should work without all the additions based on how mono searches for names in DllImport. There are additional considerations for the new dnx runtimes that I've mentioned in https://github.com/ilyalukyanov/Lightning.NET/issues/48

**Comment by CoreyKaylor** [comment]
Mono on *nix is working on the dnx branch and I have tests covered on travis-ci. Closing this, but if you notice anything specific that isn't working feel free to open up another pull request. Thanks

**Pull request closed without merging**
