### PR TITLE
Fixed copying native libraries into output directory

### LINKED ISSUE #92: Unable to load DLL 'lmdb': The specified module could not be found
LightningDB installed via NuGet installs several versions of lmdb.dll in *./packages/runtimes/os/native* path, however they are not copied to build directory. If it's not a bug, it should be at least stated explicitly with the path, where this library could be found.

### PR DESCRIPTION
**Pull request by hey-red**
Fix #92

### CODE REVIEW

**Comment by CoreyKaylor** [comment]
Nice, I noticed this approach in another project and hadn't had time to digest. I was going to mention to handle the dylib on MacOS as well, but coreclr already loads the native libs from the package path. I haven't really bothered with mono due to historical challenges in general.

**Comment by CoreyKaylor** [comment]
Closed via rebase be15808

Thanks!

**Comment by sebastienros** [comment]
@CoreyKaylor side question. what do you mean by "closed via rebase". Should I understand that you didn't "merge" the PR but rebased the commits from one repository to the other?

**Comment by hey-red** [comment]
@CoreyKaylor
I didn't check the work in mono. It's just a fix for full .NET.

**Comment by CoreyKaylor** [comment]
@sebastienros it means I rebased the PR on the latest master branch before merging. I mentioned it because the original PR came from @hey-red master branch so next time they pull from this remote it will cause issues.

**Pull request closed without merging**
