### PR TITLE
Added rakefile, converted to NUnit, created nuget package

### PR DESCRIPTION
**Pull request by CoreyKaylor**
This relates to #3 #5 #2 

I have converted to NUnit and added the rakefile. I still need to handle the native compiling next. All tests still pass.

To run you'll currently need ruby, and the bundler gem installed. After that from the directory run either "rake", or "rake ci" The former will compile and run the tests and the latter will do both and produce in the artfacts directory the nuget package.

### CODE REVIEW

**Comment by CoreyKaylor** [comment]
Yeah, I agree on the URL. Oversight on my part.

**Comment by CoreyKaylor** [comment]
My only concern is that when running that performance project I get a failed assertion dialog that pops up. Wasn't sure if that found a legitimate problem or if it was a problem with the performance test itself.

**Comment by ilyalukyanov** [comment]
About an assertion.
Did you get lmdb.dll from the repo or from somewhere else? I had a similar issue when i ran it with wrong compiled dll. Maybe i didn't put the correct one in the repository. Didn't you remember the text of an assertion?

**Comment by ilyalukyanov** [comment]
About my question about line endings.
I see now that you just moved these files. This is an answer)

**Comment by CoreyKaylor** [comment]
Yeah, I moved things around to follow an existing folder structure that keeps the root folder less bloated from all the moving parts.

It was running from the included Binaries folder. 

---

## Microsoft Visual C++ Runtime Library

Assertion failed!

Program: ...NET\src\LightningDB.Performance\bin\Debug\lmdb.DLL
File: mdb.c
Line: 2231

Expression: oldpg_txnid <= env->me_pglast

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts

## (Press Retry to debug the application - JIT must be enabled)

## Abort   Retry   Ignore

**Comment by CoreyKaylor** [comment]
Wow markdown syntax picked up a few extras there. I'm sure you still get the point.

**Comment by ilyalukyanov** [comment]
Yes, this is what i thought it could be. I think it's because old version of dll is used. I'll check it soon. 99% that if i rebuild the dll the assertion will disapear.

**Pull request merged**
